---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-generate-subnets
  annotations:
    xrender.crossplane.io/runtime: Development
spec:
  package: docker.io/choclab/function-generate-subnets:v0.0.3
  runtimeConfigRef:
    name: aws-importer-functions
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-describe-nodegroups
  annotations:
    xrender.crossplane.io/runtime: Development
spec:
  package: docker.io/choclab/function-describe-nodegroups:v0.0.28
  runtimeConfigRef:
    name: aws-importer-functions

---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1
