---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-import
spec:
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/crossplane-assume-role
  assumeRoleChain:
    - roleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-import-crossplane-role