---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-adoption
spec:
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/crossplane-assume-role
  assumeRoleChain:
    - roleARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-adoption-crossplane-role
