---
# Defines an EKS cluster importer
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksimporters.crossplane.giantswarm.io
spec:
  connectionSecretKeys:
    - kubeconfig
  defaultCompositionRef:
    name: aws-eks-import
  group: crossplane.giantswarm.io
  names:
    kind: CompositeEksImport
    plural: xeksimporters
  claimNames:
    kind: EksImportClaim
    plural: eksimportclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  description: Name of this instance that other objects will use to refer to it.
                  type: string
                namespace:
                  description: The namespace to create objects in
                  type: string
                labels:
                  description: A set of labels to apply to all resources
                  type: object
                  additionalProperties: true
                kubernetesAdditionalLabels:
                  description: A set of labels to apply to all objects created by the kubernetes provider
                  type: object
                  additionalProperties: true
                parameters:
                  type: object
                  properties:
                    awsProviderConfigRef:
                      description: The name of the provider config to use for AWS
                      type: string
                    kubernetesProviderConfigRef:
                      description: The name of the provider config to use for kubernetes
                      type: string

                    deletionPolicy:
                      description: Set the reclaim policy type for resources
                      type: string
                      default: Delete
                      enum:
                        - Delete
                        - Orphan
                    clusterName:
                      description: The ID of the EKS cluster to be imported
                      type: string
                    nodeGroupName:
                      description: The name of the nodegroup used by this cluster
                      type: string
                    region:
                      description: The region the cluster is located in
                      type: string
                  required:
                    - clusterName
                    - nodeGroupName
                    - region
                    - awsProviderConfigRef
                    - kubernetesProviderConfigRef
              required:
                - namespace
                - labels
                - kubernetesAdditionalLabels
                - parameters
            status:
              type: object
              properties:
                vpcId:
                  type: string
                  description: The ID of the VPC the cluster is located in
                endpoint:
                  type: string
                  description: The endpoint of the EKS cluster
                serviceCidrBlock:
                  type: string
                  description: The CIDR range used for EKS services
                podCidr:
                  type: string
                  description: The CIDR range used for EKS pods (comes from cluster VPC)
                subnetIds:
                  type: array
                  items:
                    type: string
                securityGroups:
                  type: object
                  description: Security groups assigned to the EKS cluster
                  properties:
                    cluster:
                      type: string
                    controlPlane:
                      type: string
                oidcIssuer:
                  type: string
                  description: The OIDC Issuer address for this cluster
                roleName:
                  type: string
                  description: The name of the role assigned to this cluster
                version:
                  type: string
                  description: The EKS version installed

                nodegroup:
                  type: object
                  properties:
                    amiType:
                      type: string
                    capacityType:
                      type: string
                    diskSize:
                      type: integer
                    scaling:
                      type: object
                      properties:
                        min:
                          type: integer
                        max:
                          type: integer
                    subnets:
                      type: array
                      items:
                        type: string
                    role:
                      type: string
                    instanceType:
                      type: string
      additionalPrinterColumns:
        - name: endpoint
          type: string
          jsonPath: ".status.endpoint"
        - name: vpcId
          type: string
          jsonPath: ".status.vpcId"
        - name: serviceCidrBlock
          type: string
          jsonPath: ".status.serviceCidrBlock"
        - name: podCidr
          type: string
          jsonPath: ".status.podCidr"
